version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "pr: dependency-update"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - "pr: dependency-update"
    schedule:
      interval: "weekly"
