version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    labels:
      - "dependency-update"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "development"
    labels:
      - "dependency-update"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/custom_components/windcentrale/"
    target-branch: "development"
    labels:
      - "dependency-update"
    schedule:
      interval: "weekly"
