blank_issues_enabled: false
contact_links:
  - name: Offical Windcentrale website
    url: https://www.windcentrale.nl/
    about: For people who want to know more about the windturbines; I'm not related to this company.
  - name: I have a question or need support
    url: https://discord.com/invite/T3tK4Jsquc
    about: Contact me on my Discord server or send a private message to me on Discord.
  - name: I'm unsure where to go
    url: https://discord.com/invite/T3tK4Jsquc
    about: If you are unsure where to go, then joining my Discord server is recommended; Just ask!
