blank_issues_enabled: false
contact_links:
  - name: Offical Windcentrale website
    url: https://www.windcentrale.nl/
    about: For people who want to know more about the windturbines; I'm not related to this company.
  - name: I have a question or need support
    url: https://discordapp.com/users/311908841459810316/
    about: Contact me by sending a message to me on Discord.
  - name: I'm unsure where to go
    url: https://discordapp.com/users/311908841459810316/
    about: If you are unsure where to go, then send me a message on Discord and I'll help you.
