name: Feature request
description: Suggest an idea for for the Home Assistant Windcentrale integration.
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        # Feature request
        
        This issue form is for feature requests only!

        If you have a found a bug or error, please use the [bug report][bug].
        If there is someting wrong with the documentation, please use the [documentation][doc].
        You just have a question for me or need support, please contact me on my [discord][dis].
        
        [bug]: https://github.com/jobvk/Home-Assistant-Windcentrale/issues/new?labels=bug&template=bug_report.yml
        [doc]: https://github.com/jobvk/Home-Assistant-Windcentrale/issues/new?labels=documentation&template=documentation_change.yml
        [dis]: https://discord.com/invite/T3tK4Jsquc
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I'm not requesting to add this integration to Home Assistant Core.
          required: true
        - label: I checked if there is not a duplicate feature request with the same question.
          required: true
        - label: I have read the paragraph ToDo on the [README.md](https://github.com/jobvk/Home-Assistant-Windcentrale/blob/master/README.md#todo) Page. And I checked if my feature request is not already there.
          required: true
        - label:  This feature request is a related to the Windcentrale integration.
          required: true
        - label: This feature request only contains 1 request (if you have multiple feature requests, open one request for each request).
          required: true
        - label: I have filled out the feature request template to the best of my ability.
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: The Feature Request
      description: >-
        Describe the feature request you would like to see to the
        maintainer.

        Provide a clear and concise description of what the feature request is.

  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    id: code-snippet
    attributes:
      label: Example Code snippet
      description: |
        If this feature request has an example piece of code that can help with this feature request, please provide.
        This can be an piece of code from, e.g., an automation, script, scene or configuration.
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: >
        If you have any additional information for the maintainer, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
